from abc import ABC, abstractmethod
from typing import List

import numpy as np


class ProblemSolver(ABC):

    @abstractmethod
    def solve(self, distance_matrix: np.ndarray, start_node: int = 1) -> List[int]:
        """ Creates path for given graph.

        :param distance_matrix: distance_matrix of given graph
        :param start_node: index of path start node
        :return: Path generated by given implementation of problem solver
        """
        pass


class SearchProblemSolver(ABC):

    @abstractmethod
    def solve(self, distance_matrix: np.ndarray, start_cycle: List[int] = None, max_time: float = None) -> List[int]:
        """ Creates path for given graph.

        :param distance_matrix: distance_matrix of given graph
        :param start_cycle: start solution to be modified by algorithm (optional)
        :param max_time: maximum execution time for given algorithm (optional)
        :return: Path generated by given implementation of problem solver
        """
        pass
